# Generated by Django 5.0.2 on 2024-12-26 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_application_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
