# Generated by Django 5.0.2 on 2024-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_application_fee_remove_job_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
